name: Deploy on DockerHub push

on:
  repository_dispatch:
    types: [dockerhub_push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ansible repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: ansible-playbook -i inventories/setup.yml deploy.yml

      - name: Debug Event
        run: echo "Triggered by event_type=${{ github.event_type }}"
