- name: Run frontend container with embedded reverse proxy
  community.docker.docker_container:
    name: frontend
    image: "{{ docker_username }}/tp-devops-frontend:latest"
    pull: true
    recreate: true
    ports:
      - "8081:80"
    networks:
      - name: my_app_network
    state: started
    restart_policy: always
