name: Build and Deploy Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mrjj001/tp-devops-simple-api:latest ./simple-api

      - name: Push image to DockerHub
        run: docker push mrjj001/tp-devops-simple-api:latest

      - name: Trigger deployment in Ansible repo
        run: |
          curl -X POST https://api.github.com/repos/njesugo/ansible/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO_B_DEPLOY_TOKEN }}" \
          -d '{"event_type": "dockerhub_push"}'