name: CI devops 2025

on:
  # Launch this job on push or pull request to main and develop
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend: 
    runs-on: ubuntu-24.04

    steps:
      # Checkout your GitHub code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify
